Library Made layout
altitlin/external-courses pull request #18
Opened 2019-04-30 21:45 UTC by altitlin

The layout of the library is rolled up, information about the books is taken from json and displayed on the site.

2019-05-01 11:09 UTC, eugrdn commented on src/library/script.js
> +var requestURL = 'https://rsu-library-api.herokuapp.com/books';
давай все, что связано с запросом, вынесем в функцию `callApi` с параметрами: 1. url, 2. колбек, 3. необязательный -- объект с настройками (метода, responseType, и пр.)

2019-05-01 11:10 UTC, eugrdn commented on src/library/script.js
> +function showBooks(jsonObj) {
у тебя коллекция, а не объект, лучше назвать booksArray, ну или производное от него

2019-05-01 11:18 UTC, eugrdn reviewed
по верстке ок, нужно только еще прижать футер к низу страницы

2019-05-01 11:18 UTC, eugrdn commented on src/library/script.js
> +    for (let i = 0; i < jsonObj.length; i++) {
почему не forEach?

2019-05-01 11:18 UTC, eugrdn commented on src/library/script.js
> +    for (let i = 0; i < jsonObj.length; i++) {
и все что ниже для каждой книги тоже бы вынести в отдельную функцию

2019-05-04 10:16 UTC, eugrdn commented
по верстке: нужно прижать футер к низу страницы, чтобы скроллились только блок с книжками и историей

2019-05-05 09:18 UTC, eugrdn commented on src/library/script.js
> +        var books = request.response;
здесь не обязательно books, ты же можешь для разного рода данных эту функцию использовать

2019-05-05 09:18 UTC, eugrdn commented on src/library/script.js
> +var request = new XMLHttpRequest();
это тоже в функцию

2019-05-09 16:33 UTC, eugrdn commented on src/library/js/script.js
> +function loadBooks() {
у тебя было же правильно, c callApi, просто объект var xhr = new XMLHttpRequest(); незачем хранть в замыкании, он новый на каждый запрос

2019-05-09 16:36 UTC, eugrdn reviewed
можешь здесь же сделать обработчики для звездочек (нужно записывать книжки куда-то, чтобы потом иметь возможность изменять рейтинг)

2019-05-09 16:36 UTC, eugrdn commented on src/library/js/script.js
> +    booksArray.forEach(function(item) {
item -> book

2019-05-12 09:46 UTC, eugrdn commented on src/library/js/Book.js
> +function Books(objBook) {
не Books, а Book

2019-05-12 09:47 UTC, eugrdn commented
скролл должен быть внутри контейнера с книгами и историей, у тебя сейчас футер прижат, но вся страница скроллится все равно
и установка рейтинга не работает сейчас

2019-05-21 16:03 UTC, eugrdn commented on src/library/js/category.js
> +        for (let i = 0; i < book.categories.length; i++) {
используй метод `.includes`

2019-05-21 16:04 UTC, eugrdn commented on src/library/js/category.js
> +    while (section.firstChild) {
section.innerHTML = ''

2019-05-21 16:06 UTC, eugrdn commented on src/library/js/filter.js
> +    var result = booksArray.filter(function(book) {
лучше 1 раз определить выбранный фильтр, затем использовать его условие в filter

2019-05-21 16:07 UTC, eugrdn commented on src/library/js/request.js
> +function loadBooks() {
должна быть общая функция, которая не знает о книгах

2019-05-29 14:33 UTC, altitlin commented
При добавлении книги она вроде добавляется, но при рендере не отображается посмотри что я не так делаю

2019-05-29 19:12 UTC, eugrdn requested changes

2019-05-29 19:12 UTC, eugrdn commented on src/library/controllers/LibraryController.js
> +(function () {
'use strict'? :)

2019-05-29 19:12 UTC, eugrdn commented on src/library/models/LibraryModel.js
> +    LibraryModel.prototype.showFree = function() {
не show, a get

2019-05-29 19:12 UTC, eugrdn commented on src/library/models/LibraryModel.js
> +    LibraryModel.prototype.showPopular = function() {
не show, a get

2019-05-29 19:12 UTC, eugrdn commented on src/library/utils/callApi.js
> +const callApi = ((url, cb) => {
лишняя скобка

2019-05-29 19:12 UTC, eugrdn commented on src/library/utils/debounce.js
> +const debounce = ((func, delay) => {
лишняя скобка

2019-05-29 19:12 UTC, eugrdn commented on src/library/models/LibraryModel.js
> +
use strict? 🙂

2019-05-29 19:12 UTC, eugrdn commented on src/library/models/LibraryModel.js
> +            if (book.categories.includes(titleCategory)) return true;
просто `return book.categories.includes(titleCategory)`

2019-05-30 21:23 UTC, altitlin commented
Итоговая версия библиотеки

2019-05-31 13:59 UTC, merged